backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "images" # Location where files will be stored in the repo

collections:
  - name: blog_posts
    label: Blog Posts
    description: Collection for managing blog posts in Decap CMS
    files: blog_posts
    fields:
      - name: title
        type: string
        label: Title
        description: The main title of the blog post
      - name: description
        type: string
        label: Description
        description: A brief summary of the blog post
      - name: pubDate
        type: date
        label: Publication Date
        description: The date the blog post was published
      - name: heroImage
        type: string
        label: Hero Image
        description: Path to the hero image for the blog post
      - name: content
        type: markdown
        label: Content
        description: The main content of the blog post in Markdown format

public_folder: "public/" # The src attribute for uploaded media
site_url: https://astro-blog-22.netlify.app
