backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "images" # Location where files will be stored in the repo

collections:
  - name: blog_posts
    label: Blog Posts
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    files: blog_posts
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

public_folder: "public/images" # The src attribute for uploaded media
site_url: https://astro-blog-22.netlify.app
